### ISSUE TITLE
CA1016 Add an AssemblyVersion attribute to 'UnitTests.dll'.

### ISSUE THREAD

**Issue by PRINCZ-Akos** [GarbageCollectorsReloaded/EmailValidation#3]

**Comment by micskeiz** [comment]
Add please a screenshot about the result of the static analysis to the appropriate wiki page.

**Comment by PRINCZ-Akos** [comment]
![Screenshot](https://cdn.discordapp.com/attachments/296641167720710145/302491685122736128/unknown.png "Static analysis results")
