### ISSUE TITLE
Run Code Coverage on https://github.com/GarbageCollectorsReloaded/EmailValidation/commit/d9c8404270790121797d13d44723561455d695d2

### ISSUE THREAD

**Issue by PRINCZ-Akos** [GarbageCollectorsReloaded/EmailValidation#5]

**Comment by Somakex** [comment]
Result of code coverage analysis on Visual Studio 2017
![Coverage](https://cdn.discordapp.com/attachments/296641167720710145/307957390836498442/unknown.png "Code coverage analysis result")

**Comment by PRINCZ-Akos** [comment]
Most of the code not covered, is not covered because the coverage tool is not able to check.
